from .mozambique import MozambiquePhoneValidator
from .angola import AngolaPhoneValidator
from .brazil import BrazilPhoneValidator
from .portugal import PortugalPhoneValidator
from .italy import ItalyPhoneValidator
from .capeverde import CapeVerdePhoneValidator
from .guineabissau import GuineaBissauPhoneValidator
from .saotome import SaoTomePhoneValidator
from .easttimor import EastTimorPhoneValidator
from .southafrica import SouthAfricaPhoneValidator
from .nigeria import NigeriaPhoneValidator
from .kenya import KenyaPhoneValidator
from .tanzania import TanzaniaPhoneValidator
from .ghana import GhanaPhoneValidator
from .ethiopia import EthiopiaPhoneValidator
from .zimbabwe import ZimbabwePhoneValidator
from .zambia import ZambiaPhoneValidator
from .egypt import EgyptPhoneValidator
from .morocco import MoroccoPhoneValidator
from .algeria import AlgeriaPhoneValidator
from .uganda import UgandaPhoneValidator
from .ivorycoast import IvoryCoastPhoneValidator
from .senegal import SenegalPhoneValidator
from .cameroon import CameroonPhoneValidator
from .rwanda import RwandaPhoneValidator
from .internacional import InternacionalPhoneValidator